name: beclean_user
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: "^0.13.1"
  jwt_decoder: ^2.0.1
  http: ^0.13.3
  shared_preferences: ^2.0.6
  provider: ^6.1.2
  awesome_dialog: ^3.2.1
  rive_common: ^0.4.11

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/iconlauncher.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/img/
